layout_spectrum: 0.217327
color:
  saturation: 0.4437015
  lightness: 0.6153646
  brandStrength: 0.2882848
  rhythmicContrast: 0.3869179
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.5430108
name: TroubleTheBand
